"""
Django settings for hotel_management project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2imd@$7&lhje=%agcza^fat5v4&)*2#p-9o!9iv3avu-zkbw!s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hotel_management_be',
    'corsheaders',
    'rest_framework',
    'drf_yasg',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    "middleware.custom_authen.EmailOrUsernameBackend",
    "django.contrib.auth.backends.ModelBackend",  # fallback
]


ROOT_URLCONF = 'hotel_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL='hotel_management_be.User'

WSGI_APPLICATION = 'hotel_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DEV_ENGINE"),
        "NAME": os.getenv("DEV_DB_NAME"),
        "USER": os.getenv("DEV_DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DEV_DB_HOST"),
        "PORT": "3306",
        "CONN_MAX_AGE": 30,
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # "LOCATION": "redis://"+os.environ.get("DEV_REDIS_CACHE_SERVER_PORT", "127.0.0.1:6379")+"/1",  # DB index 1
        "LOCATION": "redis://"
        + os.getenv("DEV_REDIS_CACHE_SERVER_PORT", "redis_hotel:6379")
        + "/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

PAYPAL_CONFIG = {
    "client_id": os.getenv("PAYPAL_CLIENT_ID"),
    "client_secret": os.getenv("PAYPAL_CLIENT_SECRET"),
    "base_url": "https://api-m.sandbox.paypal.com"  # sandbox endpoint
}

VNPAY_CONFIG = {
    "vnp_TmnCode": os.getenv("VNPAY_TMN_CODE"),
    "vnp_HashSecret": os.getenv("VNPAY_HASH_SECRET"),
    "vnp_Url": os.getenv("VNPAY_PAYMENT_URL"),
    "vnp_ReturnUrl": os.getenv("VNPAY_RETURN_URL")
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "assets"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "exceptions.exception_handler.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "middleware.jwt_middleware.CustomJWTAuthentication",
    ),
  
    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "ALGORITHM": "HS256",
    "UPDATE_LAST_LOGIN": True,
    "SIGNING_KEY": SECRET_KEY,
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

OPTIONS = {
    "charset": "utf8mb4",
    "use_unicode": True,
}

# Redis cho Channels (nếu dùng)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{
                "address": ("redis", 6379),
                "db": 2,  # 👉 chọn database Redis số 1
            }],
        },
    },
}
# EMAIL_USE_UTF8 = True
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = os.getenv("EMAIL_HOST_DEV")
# EMAIL_PORT = os.getenv("EMAIL_PORT_DEV")
# EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS_DEV")
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER_DEV")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD_DEV")
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Swagger Settings
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT token. Format: Bearer <token>",
        }
    },
    "DEFAULT_API_URL": "http://localhost:8000",
    "USE_SESSION_AUTH": False,
}
CELERY_BROKER_URL = "redis://redis_hotel:6379/0"
CELERY_BEAT_SCHEDULE = {
    'reconcile-expired-holds-every-minute': {
        'task': 'hotel_management_be.celery_hotel.task.reconcile_expired_holds',
        'schedule': 30.0,
    },
    'cleanup-old-inventory-daily': {
        'task': 'hotel_management_be.celery_hotel.task.cleanup_old_inventory',
        'schedule': 86400.0,  # chạy 1 lần/ngày
    },
}
CELERY_RESULT_BACKEND = "redis://redis_hotel:6379/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_IGNORE_RESULT = True
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

REDIS_URL=os.getenv('REDIS_URL')

KAFKA_BOOTSTRAP_SERVERS = os.getenv('KAFKA_BOOTSTRAP_SERVERS')
KAFKA_TOPIC = "booking_events"
KAFKA_GROUP_ID = "booking_service_group"


GOOGLE_CLIENT_ID = '601097463713-msqb22gt741bck3n9fr0ci5mo8u4msne.apps.googleusercontent.com'

#AI
CHROMA_PATH = './chroma_db'
GROQ_API_KEY = os.getenv('API_KEY_GROQ')